# data & model
dim: 256
n_mels: 80
sr: 16000
n_fft: 1024
win_size: 1024
hop_size: 160
max_mel_len: 4096
max_text_len: 100
cache_dir: "vendor"

# training
max_epoch: 10
lr: 1.0e-3
decay: 0.75
batch_size: 32
num_workers: 4
